In [1]:
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

# Some texts of different lengths.
english_sentences = ["dog", "Puppies are nice.", "I enjoy taking long walks along the beach with my dog."]
italian_sentences = ["cane", "I cuccioli sono carini.", "Mi piace fare lunghe passeggiate lungo la spiaggia con il mio cane."]
japanese_sentences = ["犬", "子犬はいいです", "私は犬と一緒にビーチを散歩するのが好きです"]

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

# Compute embeddings.
en_result = embed(english_sentences)
it_result = embed(italian_sentences)
ja_result = embed(japanese_sentences)

# Compute similarity matrix. Higher score indicates greater similarity.
similarity_matrix_it = np.inner(en_result, it_result)
similarity_matrix_ja = np.inner(en_result, ja_result)

In [2]:
print(en_result)

tf.Tensor(
[[-0.00525213 -0.038312   -0.00922012 ...  0.02179049  0.06280179
  -0.01622537]
 [-0.02267585 -0.06907186  0.0155087  ...  0.087623   -0.00076925
  -0.05410822]
 [ 0.01908831  0.00955222 -0.0474129  ...  0.03206478  0.03661669
   0.00331059]], shape=(3, 512), dtype=float32)


In [3]:
print(similarity_matrix_it)


[[0.9696458  0.27347842 0.25536823]
 [0.37726057 0.8931676  0.28806686]
 [0.24611366 0.2379298  0.9352151 ]]
